- name: "generate hpool config.yml"
  template: src=hpool_config.j2 dest=~/{{ inventory_hostname }}/hpool_conf.yml

# join HPool
- name: "join hpool to mine XCH"
  shell: "sh ./chia_join_hpool.sh {{ inventory_hostname }}/hpool_conf.yml >/dev/null 2>&1 &)"
  async: 5
  poll: 0